# Generated by Django 5.2 on 2025-05-16 18:41

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_examen', '0009_alter_biomicroscopy_segment_anterieur_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('antecedents_medico_chirurgicaux', models.TextField(verbose_name='Antécédents médico-chirurgicaux')),
                ('pathologie_ophtalmologique', models.TextField(verbose_name='Pathologies ophtalmologiques')),
                ('addiction', models.BooleanField(default=False, verbose_name='Addiction')),
                ('type_addiction', models.CharField(choices=[('tabagisme', 'Tabagisme'), ('alcool', 'Alcool'), ('telephone', 'Téléphone portable'), ('other', 'Autres')], max_length=15, null=True, verbose_name="Type d'addiction")),
                ('autre_addiction_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre addiction (si sélectionné)')),
                ('tabagisme_detail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tabagisme (paquets/année)')),
                ('familial', models.CharField(choices=[('cecité', 'Cécité'), ('gpao', 'GPAO'), ('other', 'Autres')], max_length=10, null=True, verbose_name='Familiaux')),
                ('autre_familial_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autres familiaux (si sélectionné)')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Antécédent',
                'verbose_name_plural': 'Antécédents',
            },
        ),
        migrations.CreateModel(
            name='DriverExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('km_parcourus', models.FloatField(null=True, verbose_name='Kilomètres parcourus')),
                ('nombre_accidents', models.PositiveIntegerField(default=0, verbose_name="Nombre d'accidents")),
                ('tranche_horaire', models.TimeField(verbose_name='Tranche horaire de conduite')),
                ('dommage', models.CharField(choices=[('corporel', 'Corporel'), ('materiel', 'Matériel')], max_length=10, null=True, verbose_name='Dommages')),
                ('degat', models.CharField(choices=[('important', 'Important'), ('modéré', 'Modéré'), ('léger', 'Léger')], max_length=10, null=True, verbose_name='Dégâts')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Expérience de conduite',
                'verbose_name_plural': 'Expériences de conduite',
                'unique_together': {('patient', 'visite')},
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('antecedant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health_record.antecedent')),
                ('clinical_examen', models.ManyToManyField(to='clinical_examen.examenclinique')),
                ('driver_experience', models.ManyToManyField(to='health_record.driverexperience')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
            },
        ),
    ]
