# Generated by Django 5.2 on 2025-06-14 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='risky_patient',
            field=models.BooleanField(default=False, verbose_name='risky patient'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='antecedents_medico_chirurgicaux',
            field=models.TextField(blank=True, verbose_name='Antécédents médico-chirurgicaux'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='autre_addiction_detail',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Détail autre addiction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='autre_familial_detail',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Détail autre familial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='familial',
            field=models.CharField(blank=True, choices=[('cecité', 'Cécité'), ('gpao', 'GPAO'), ('other', 'Autres')], max_length=10, null=True, verbose_name='Antécédents familiaux'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='pathologie_ophtalmologique',
            field=models.TextField(blank=True, verbose_name='Pathologies ophtalmologiques'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='patients.conducteur'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='tabagisme_detail',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Tabagisme (paquets/année)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='type_addiction',
            field=models.CharField(blank=True, choices=[('tabagisme', 'Tabagisme'), ('alcool', 'Alcool'), ('telephone', 'Téléphone portable'), ('other', 'Autres')], max_length=15, null=True, verbose_name="Type d'addiction"),
        ),
    ]
