# Generated by Django 5.2 on 2025-06-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedent',
            name='familial',
            field=models.CharField(blank=True, choices=[('CECITE', 'CECITE'), ('GPAO', 'GPAO'), ('OTHER', 'OTHER')], max_length=10, null=True, verbose_name='Antécédents familiaux'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='type_addiction',
            field=models.CharField(blank=True, choices=[('TABAGISME', 'TABAGISME'), ('ALCOOL', 'ALCOOL'), ('TELEPHONE', 'TELEPHONE'), ('OTHER', 'OTHER')], max_length=15, null=True, verbose_name="Type d'addiction"),
        ),
        migrations.AlterField(
            model_name='driverexperience',
            name='degat',
            field=models.CharField(blank=True, choices=[('IMPORTANT', 'IMPORTANT'), ('MODERE', 'MODERE'), ('LEGER', 'LEGER')], max_length=10, null=True, verbose_name='Dégâts'),
        ),
        migrations.AlterField(
            model_name='driverexperience',
            name='dommage',
            field=models.CharField(blank=True, choices=[('CORPOREL', 'CORPOREL'), ('MATERIEL', 'MATERIEL')], max_length=10, null=True, verbose_name='Dommages'),
        ),
        migrations.AlterField(
            model_name='driverexperience',
            name='visite',
            field=models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')], db_index=True),
        ),
    ]
