# Generated by Django 5.2 on 2025-06-25 22:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0002_alter_antecedent_familial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverexperience',
            name='dommage',
        ),
        migrations.AddField(
            model_name='driverexperience',
            name='corporel_dommage',
            field=models.BooleanField(default=False, verbose_name='Dommage corporel'),
        ),
        migrations.AddField(
            model_name='driverexperience',
            name='corporel_dommage_type',
            field=models.CharField(blank=True, choices=[('IMPORTANT', 'IMPORTANT'), ('MODERE', 'MODERE'), ('LEGER', 'LEGER')], null=True, verbose_name='Type de dommage corporel'),
        ),
        migrations.AddField(
            model_name='driverexperience',
            name='date_dernier_accident',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date du dernier accident'),
        ),
        migrations.AddField(
            model_name='driverexperience',
            name='deces_cause',
            field=models.CharField(blank=True, choices=[('MORT_NATUREL', 'MORT_NATUREL'), ('ACCIDENT', 'ACCIDENT'), ('NON_PRECESEE', 'NON_PRECESEE')], max_length=255, null=True, verbose_name='Cause du décès'),
        ),
        migrations.AddField(
            model_name='driverexperience',
            name='etat_conducteur',
            field=models.CharField(choices=[('DECEDE', 'DECEDE'), ('PERTE_DE_VUE', 'PERTE_DE_VUE'), ('ACTIF', 'ACTIF'), ('INACTIF', 'INACTIF')], default='ACTIF', max_length=50, verbose_name='État du conducteur'),
        ),
        migrations.AddField(
            model_name='driverexperience',
            name='inactif_cause',
            field=models.CharField(blank=True, choices=[('MALADIE', 'MALADIE'), ('ACCIDENT', 'ACCIDENT'), ('AUTRE', 'AUTRE'), ('CHOMAGE', 'CHOMAGE')], max_length=255, null=True, verbose_name="Cause de l'inactivité"),
        ),
        migrations.AddField(
            model_name='driverexperience',
            name='materiel_dommage',
            field=models.BooleanField(default=False, verbose_name='Dommage matériel'),
        ),
        migrations.AddField(
            model_name='driverexperience',
            name='materiel_dommage_type',
            field=models.CharField(blank=True, choices=[('IMPORTANT', 'IMPORTANT'), ('MODERE', 'MODERE'), ('LEGER', 'LEGER')], null=True, verbose_name='Type de dommage matériel'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='familial',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CECITE', 'CECITE'), ('GPAO', 'GPAO'), ('OTHER', 'OTHER')], max_length=18, verbose_name='Antécédents familiaux'), blank=True, default=list, size=None, verbose_name='Antécédents familiaux'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='type_addiction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TABAGISME', 'TABAGISME'), ('ALCOOL', 'ALCOOL'), ('TELEPHONE', 'TELEPHONE'), ('OTHER', 'OTHER'), ('SANS_PARTICULARITE', 'SANS_PARTICULARITE')], max_length=18, verbose_name="Type d'addiction"), blank=True, default=list, size=None, verbose_name="Types d'addiction"),
        ),
    ]
