# Generated by Django 5.2 on 2025-06-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0002_healthrecord_risky_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverexperience',
            name='date_visite',
            field=models.DateField(default=None, null=True, verbose_name='Date de visite'),
        ),
    ]
