# Generated by Django 5.2 on 2025-06-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0003_remove_driverexperience_dommage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverexperience',
            name='degat',
        ),
    ]
