# Generated by Django 5.2 on 2025-06-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0003_driverexperience_date_visite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverexperience',
            name='tranche_horaire',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tranche horaire de conduite'),
        ),
    ]
