# Generated by Django 5.2 on 2025-06-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0004_alter_driverexperience_tranche_horaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='sExamenss',
            new_name='examens',
        ),
    ]
