# Generated by Django 5.2 on 2025-05-15 17:05

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('od', models.FloatField(blank=True, null=True, verbose_name='OD (œil droit)')),
                ('og', models.FloatField(blank=True, null=True, verbose_name='OG (œil gauche)')),
                ('segment', models.CharField(choices=[('NORMAL', 'Normal'), ('PRESENCE LESION', 'Presence lesion'), ('REMANIEMENT TOTAL', 'Remanement total')], max_length=20, verbose_name='Segment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'abstract': False,
                'unique_together': {('patient', 'visite')},
            },
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('vision', models.CharField(choices=[('compatible', 'Compatible'), ('incompatible', 'Incompatible'), ('a_risque', 'À risque')], max_length=50, null=True, verbose_name='Conclusion sur la conduite')),
                ('cat', models.TextField(null=True, verbose_name='CAT')),
                ('traitement', models.TextField(null=True, verbose_name='Traitement')),
                ('observation', models.TextField(null=True, verbose_name='Observation')),
                ('rv', models.BooleanField(default=False, help_text='6 mois avec True, moins de 6 mois avec False', verbose_name='RV')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Conclusion',
                'verbose_name_plural': 'Conclusions',
            },
        ),
        migrations.CreateModel(
            name='OcularTension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('od', models.FloatField(blank=True, null=True, verbose_name='OD (œil droit)')),
                ('og', models.FloatField(blank=True, null=True, verbose_name='OG (œil gauche)')),
                ('ttt_hypotonisant', models.BooleanField(default=False, verbose_name='TTT hypotonisant appliqué')),
                ('ttt_hypotonisant_value', models.CharField(choices=[('BBLOQUANTS', 'BBLOQUANTS'), ('IAC', 'IAC'), ('PROSTAGLANDINES', 'PROSTAGLANDINES'), ('PILOCARPINE', 'PILOCARPINE'), ('AUTRES', 'AUTRES')], max_length=30, verbose_name='TTT hypotonisant value')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Tonus oculaire',
                'verbose_name_plural': 'Tonus oculaires',
            },
        ),
        migrations.CreateModel(
            name='Pachymetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('od', models.FloatField(blank=True, null=True, verbose_name='OD (œil droit)')),
                ('og', models.FloatField(blank=True, null=True, verbose_name='OG (œil gauche)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Pachymétrie',
                'verbose_name_plural': 'Pachymétries',
            },
        ),
        migrations.CreateModel(
            name='Perimetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('pbo', models.CharField(choices=[('Normal', 'Normal'), ('Scotome central', 'Scotome central'), ('Scotome périphérique', 'Scotome périphérique'), ('Amputation', 'Amputation')], max_length=30, null=True, verbose_name='PBO')),
                ('limite_superieure', models.FloatField(null=True, verbose_name='Limite supérieure (en degré)')),
                ('limite_inferieure', models.FloatField(null=True, verbose_name='Limite inférieure (en degré)')),
                ('limite_temporale_droit', models.FloatField(null=True, verbose_name='Limite Temporale  droite')),
                ('limite_temporale_gauche', models.FloatField(null=True, verbose_name='Limite Temporale gauche')),
                ('limite_horizontal', models.FloatField(null=True, verbose_name='Limite Horizontal')),
                ('score_esternmen', models.FloatField(null=True, verbose_name='Score d’Estermen (pourcentage)')),
                ('image', models.ImageField(upload_to='images/perimetries_binoculaire/', verbose_name='Image')),
                ('images', models.FileField(upload_to='images/perimetries_binoculaire/', verbose_name='Images')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Périmétrie binoculaire',
                'verbose_name_plural': 'Périmétries binoculaires',
            },
        ),
        migrations.CreateModel(
            name='Plaintes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('od_symptom', models.CharField(choices=[('AUCUN', 'Aucun'), ('BAV', 'BAV'), ('ROUGEUR', 'ROUGEUR'), ('DOULEUR', 'DOULEUR'), ('DIPLOPIE', 'DIPLOPIE'), ('STARBISME', 'STARBISME'), ('NYSTAGMUS', 'NYSTAGMUS'), ('PTOSIS', 'PTOSIS'), ('AUTRES', 'AUTRES')], max_length=30, verbose_name='OD symptom')),
                ('og_symptom', models.CharField(choices=[('AUCUN', 'Aucun'), ('BAV', 'BAV'), ('ROUGEUR', 'ROUGEUR'), ('DOULEUR', 'DOULEUR'), ('DIPLOPIE', 'DIPLOPIE'), ('STARBISME', 'STARBISME'), ('NYSTAGMUS', 'NYSTAGMUS'), ('PTOSIS', 'PTOSIS'), ('AUTRES', 'AUTRES')], max_length=30, verbose_name='OG symptom')),
                ('diplopie', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], null=True, verbose_name='Diplopie')),
                ('diplopie_type', models.CharField(choices=[('monoculaire', 'Monoculaire'), ('binoculaire', 'Binoculaire')], max_length=20, null=True, verbose_name='Diplopie type')),
                ('strabisme', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], null=True, verbose_name='Strabisme')),
                ('strabisme_eye', models.CharField(choices=[('od', 'OD'), ('og', 'OG'), ('odg', 'ODG')], max_length=20, null=True, verbose_name='Œil affecté par strabisme')),
                ('nystagmus', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], null=True, verbose_name='Nystagmus')),
                ('nystagmus_eye', models.CharField(choices=[('od', 'OD'), ('og', 'OG'), ('odg', 'ODG')], max_length=20, null=True, verbose_name='Œil affecté par nystagmus')),
                ('ptosis', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], null=True, verbose_name='Ptosis')),
                ('ptosis_eye', models.CharField(choices=[('od', 'OD'), ('og', 'OG'), ('odg', 'ODG')], max_length=20, null=True, verbose_name='Œil affecté par ptosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Examen clinique - Diplopie, Strabisme, Nystagmus, Ptosis',
                'verbose_name_plural': 'Examens cliniques - Diplopie, Strabisme, Nystagmus, Ptosis',
            },
        ),
        migrations.CreateModel(
            name='Refraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('od_s', models.FloatField(null=True, verbose_name='S OD')),
                ('od_c', models.FloatField(null=True, verbose_name='C OD')),
                ('od_a', models.FloatField(null=True, verbose_name='A OD')),
                ('og_s', models.FloatField(null=True, verbose_name='S OG')),
                ('og_c', models.FloatField(null=True, verbose_name='C OG')),
                ('og_a', models.FloatField(null=True, verbose_name='A OG')),
                ('dp', models.FloatField(null=True, verbose_name='DP en mm')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Réfraction automatisée',
                'verbose_name_plural': 'Réfractions automatisées',
            },
        ),
        migrations.CreateModel(
            name='SegmentAnterieur',
            fields=[
                ('segment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinical_examen.segment')),
                ('cornee', models.CharField(choices=[('Normal', 'Normal'), ('Opacité Axe', 'Opacité - Axe'), ('Opacité Périphérie', 'Opacité - Périphérie'), ('Opacité Totale', 'Opacité - Totale'), ('Autre', 'Autre')], max_length=30, verbose_name='Corne')),
                ('profondeur', models.CharField(choices=[('Normale', 'Normale'), ('Réduite', 'Réduite'), ('Augmentée', 'Augmentée'), ('Asymétrique', 'Asymétrique')], max_length=30, verbose_name='Profondeur')),
                ('transparence', models.CharField(choices=[('Normal', 'Normal'), ('Anormale', 'Anormale')], max_length=30, verbose_name='Transparence')),
                ('type_anomalie_value', models.CharField(choices=[('Pigments', 'Pigments'), ('Hyphéma', 'Hyphéma'), ('Hypopion', 'Hypopion'), ('Autre', 'Autre')], max_length=30, null=True, verbose_name='Anormal transparence')),
                ('quantite_anomalie', models.CharField(choices=[('Minime', 'Minime'), ('Atteignant air pupillaire', 'Atteignant air pupillaire'), ('Recouvrant pupille', 'Recouvrant pupille')], max_length=30, null=True, verbose_name='quantité anomalie')),
                ('pupille', models.CharField(choices=[('Normal', 'Normal'), ('Myosis', 'Myosis'), ('Mydriase', 'Mydriase')], max_length=30, verbose_name='Pupille')),
                ('axe_visuel', models.CharField(choices=[('Dégagé', 'Dégagé'), ('Obstrué', 'Obstrué'), ('Leucocorie', 'Leucocorie')], max_length=30, verbose_name='Axe Visuel')),
                ('rpm', models.CharField(choices=[('Normal', 'Normal'), ('Lent', 'Lent'), ('Aboli', 'Aboli')], max_length=30, verbose_name='RPM')),
                ('iris', models.CharField(choices=[('Normal', 'Normal'), ('Iridodonésis', 'Iridodonésis'), ('Rubéose', 'Rubéose'), ('Synéchies', 'Synéchies'), ('Autres', 'Autres')], max_length=30, verbose_name='Iris')),
                ('cristallin', models.CharField(choices=[('Normal', 'Normal'), ('Opaque', 'Opaque'), ('Colobome', 'Colobome'), ('Aphakie', 'Aphakie'), ('Pseudophakie', 'Pseudophakie')], max_length=30, verbose_name='Cristallin')),
                ('position_cristallin', models.CharField(choices=[('Normale', 'Normale'), ('Ectopie', 'Ectopie'), ('Luxation/subluxation antérieure', 'Luxation/subluxation antérieure'), ('Luxation/subluxation postérieure', 'Luxation/subluxation postérieure')], max_length=32, verbose_name='Position Cristallin')),
            ],
            options={
                'verbose_name': 'Segment antérieur (SA)',
                'verbose_name_plural': 'Segment antérieurs (SA)',
            },
            bases=('clinical_examen.segment',),
        ),
        migrations.CreateModel(
            name='SegmentPosterieur',
            fields=[
                ('segment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinical_examen.segment')),
                ('vitre', models.CharField(choices=[('Normal', 'Normal'), ('Corps flottants', 'Corps flottants'), ('Hémorragie', 'Hémorragie'), ('Hyalite', 'Hyalite'), ('PVR', 'PVR'), ('Autres', 'Autres')], max_length=30, verbose_name='Vitre')),
                ('retine', models.FloatField(verbose_name='Rétine')),
                ('papille', models.CharField(choices=[('Normale', 'Normale'), ('Excavation élargie', 'Excavation élargie'), ('Atrophie', 'Atrophie'), ('Œdème', 'Œdème'), ('Dysmorphie', 'Dysmorphie'), ('Autres', 'Autres')], max_length=30, verbose_name='Papille')),
                ('macula', models.CharField(choices=[('Normal', 'Normal'), ('Cicatrice', 'Cicatrice'), ('Œdème', 'Œdème'), ('DMLA', 'DMLA')], max_length=30, verbose_name='Macula')),
                ('retinien_peripherique', models.CharField(choices=[('Normal', 'Normal'), ('Cicatrice', 'Cicatrice'), ('Œdème', 'Œdème'), ('Hémorragie', 'Hémorragie'), ('Exudats', 'Exudats'), ('Autre', 'Autre')], max_length=30, verbose_name='Champ rétinien périphérique')),
                ('vaissaux', models.CharField(choices=[('Normaux', 'Normaux'), ('Artériosclérose', 'Artériosclérose'), ('OVR', 'OVR'), ('OAR', 'OAR'), ('Néovaisseux', 'Néovaisseux')], max_length=30, verbose_name='Vaissaux')),
            ],
            options={
                'verbose_name': 'Segment antérieur (SA)',
                'verbose_name_plural': 'Segment antérieurs (SA)',
            },
            bases=('clinical_examen.segment',),
        ),
        migrations.CreateModel(
            name='VisualAcuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('avsc_od', models.CharField(max_length=100, verbose_name='AVSC OD')),
                ('avsc_og', models.CharField(max_length=100, verbose_name='AVSC OG')),
                ('avsc_dg', models.CharField(max_length=100, verbose_name='AVSC ODG')),
                ('avac_od', models.CharField(max_length=100, verbose_name='AVAC OD')),
                ('avac_og', models.CharField(max_length=100, verbose_name='AVAC OG')),
                ('avac_dg', models.CharField(max_length=100, verbose_name='AVAC ODG')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
            ],
            options={
                'verbose_name': 'Acuité visuelle',
                'verbose_name_plural': 'Acuités visuelles',
            },
        ),
        migrations.CreateModel(
            name='Biomicroscopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
                ('segment_anterieur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_examen.segmentanterieur')),
                ('segment_posterieur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_examen.segmentposterieur')),
            ],
            options={
                'verbose_name': 'Biomicroscopie (SA + SP)',
                'verbose_name_plural': 'Biomicroscopies (SA + SP)',
            },
        ),
        migrations.CreateModel(
            name='ExamenClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visite', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon Technique'), ('tech_review', 'Prêt pour Médecin'), ('md_review', 'En Revue Clinique'), ('completed', 'Terminé')], default='draft', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('biomicroscopy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_examen.biomicroscopy')),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_examen.conclusion')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.conducteur')),
                ('ocular_tension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_examen.oculartension')),
                ('pachymetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_examen.pachymetry')),
                ('perimetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_examen.perimetry')),
                ('plaintes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_examen.plaintes')),
                ('refraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_examen.refraction')),
                ('visualAcuity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_examen.visualacuity')),
            ],
            options={
                'verbose_name': 'Examen Clinique',
                'verbose_name_plural': 'Examens Cliniques',
                'unique_together': {('patient', 'visite')},
            },
        ),
    ]
