# Generated by Django 5.2 on 2025-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_examen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oculartension',
            name='ttt_hypotonisant_value',
            field=models.CharField(choices=[('BBLOQUANTS', 'BBLOQUANTS'), ('IAC', 'IAC'), ('PROSTAGLANDINES', 'PROSTAGLANDINES'), ('PILOCARPINE', 'PILOCARPINE'), ('AUTRES', 'AUTRES')], max_length=30, null=True, verbose_name='TTT hypotonisant value'),
        ),
        migrations.AlterField(
            model_name='plaintes',
            name='diplopie',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='Diplopie'),
        ),
        migrations.AlterField(
            model_name='plaintes',
            name='nystagmus',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='Nystagmus'),
        ),
        migrations.AlterField(
            model_name='plaintes',
            name='ptosis',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='Ptosis'),
        ),
        migrations.AlterField(
            model_name='plaintes',
            name='strabisme',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='Strabisme'),
        ),
    ]
