# Generated by Django 5.2 on 2025-05-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_examen', '0003_alter_oculartension_ttt_hypotonisant_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oculartension',
            name='ttt_hypotonisant_value',
            field=models.CharField(blank=True, choices=[('BBLOQUANTS', 'BBLOQUANTS'), ('IAC', 'IAC'), ('PROSTAGLANDINES', 'PROSTAGLANDINES'), ('PILOCARPINE', 'PILOCARPINE'), ('AUTRES', 'AUTRES')], default=None, max_length=30, null=True, verbose_name='TTT hypotonisant value'),
        ),
    ]
