# Generated by Django 5.2 on 2025-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_examen', '0004_alter_oculartension_ttt_hypotonisant_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaintes',
            name='diplopie_type',
            field=models.CharField(blank=True, choices=[('monoculaire', 'Monoculaire'), ('binoculaire', 'Binoculaire')], max_length=20, null=True, verbose_name='Diplopie type'),
        ),
        migrations.AlterField(
            model_name='plaintes',
            name='nystagmus_eye',
            field=models.CharField(blank=True, choices=[('od', 'OD'), ('og', 'OG'), ('odg', 'ODG')], max_length=20, null=True, verbose_name='Œil affecté par nystagmus'),
        ),
        migrations.AlterField(
            model_name='plaintes',
            name='ptosis_eye',
            field=models.CharField(blank=True, choices=[('od', 'OD'), ('og', 'OG'), ('odg', 'ODG')], max_length=20, null=True, verbose_name='Œil affecté par ptosis'),
        ),
        migrations.AlterField(
            model_name='plaintes',
            name='strabisme_eye',
            field=models.CharField(blank=True, choices=[('od', 'OD'), ('og', 'OG'), ('odg', 'ODG')], max_length=20, null=True, verbose_name='Œil affecté par strabisme'),
        ),
    ]
