# Generated by Django 5.2 on 2025-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_examen', '0005_alter_plaintes_diplopie_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentanterieur',
            name='axe_visuel',
            field=models.CharField(blank=True, choices=[('Dégagé', 'Dégagé'), ('Obstrué', 'Obstrué'), ('Leucocorie', 'Leucocorie')], max_length=30, verbose_name='Axe Visuel'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='cornee',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Opacité Axe', 'Opacité - Axe'), ('Opacité Périphérie', 'Opacité - Périphérie'), ('Opacité Totale', 'Opacité - Totale'), ('Autre', 'Autre')], max_length=30, verbose_name='Corne'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='cristallin',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Opaque', 'Opaque'), ('Colobome', 'Colobome'), ('Aphakie', 'Aphakie'), ('Pseudophakie', 'Pseudophakie')], max_length=30, verbose_name='Cristallin'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='iris',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Iridodonésis', 'Iridodonésis'), ('Rubéose', 'Rubéose'), ('Synéchies', 'Synéchies'), ('Autres', 'Autres')], max_length=30, verbose_name='Iris'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='position_cristallin',
            field=models.CharField(blank=True, choices=[('Normale', 'Normale'), ('Ectopie', 'Ectopie'), ('Luxation/subluxation antérieure', 'Luxation/subluxation antérieure'), ('Luxation/subluxation postérieure', 'Luxation/subluxation postérieure')], max_length=32, verbose_name='Position Cristallin'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='profondeur',
            field=models.CharField(blank=True, choices=[('Normale', 'Normale'), ('Réduite', 'Réduite'), ('Augmentée', 'Augmentée'), ('Asymétrique', 'Asymétrique')], max_length=30, verbose_name='Profondeur'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='pupille',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Myosis', 'Myosis'), ('Mydriase', 'Mydriase')], max_length=30, verbose_name='Pupille'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='quantite_anomalie',
            field=models.CharField(blank=True, choices=[('Minime', 'Minime'), ('Atteignant air pupillaire', 'Atteignant air pupillaire'), ('Recouvrant pupille', 'Recouvrant pupille')], max_length=30, null=True, verbose_name='quantité anomalie'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='rpm',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Lent', 'Lent'), ('Aboli', 'Aboli')], max_length=30, verbose_name='RPM'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='transparence',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Anormale', 'Anormale')], max_length=30, verbose_name='Transparence'),
        ),
        migrations.AlterField(
            model_name='segmentanterieur',
            name='type_anomalie_value',
            field=models.CharField(blank=True, choices=[('Pigments', 'Pigments'), ('Hyphéma', 'Hyphéma'), ('Hypopion', 'Hypopion'), ('Autre', 'Autre')], max_length=30, null=True, verbose_name='Anormal transparence'),
        ),
        migrations.AlterField(
            model_name='segmentposterieur',
            name='macula',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Cicatrice', 'Cicatrice'), ('Œdème', 'Œdème'), ('DMLA', 'DMLA')], max_length=30, verbose_name='Macula'),
        ),
        migrations.AlterField(
            model_name='segmentposterieur',
            name='papille',
            field=models.CharField(blank=True, choices=[('Normale', 'Normale'), ('Excavation élargie', 'Excavation élargie'), ('Atrophie', 'Atrophie'), ('Œdème', 'Œdème'), ('Dysmorphie', 'Dysmorphie'), ('Autres', 'Autres')], max_length=30, verbose_name='Papille'),
        ),
        migrations.AlterField(
            model_name='segmentposterieur',
            name='retinien_peripherique',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Cicatrice', 'Cicatrice'), ('Œdème', 'Œdème'), ('Hémorragie', 'Hémorragie'), ('Exudats', 'Exudats'), ('Autre', 'Autre')], max_length=30, verbose_name='Champ rétinien périphérique'),
        ),
        migrations.AlterField(
            model_name='segmentposterieur',
            name='vaissaux',
            field=models.CharField(blank=True, choices=[('Normaux', 'Normaux'), ('Artériosclérose', 'Artériosclérose'), ('OVR', 'OVR'), ('OAR', 'OAR'), ('Néovaisseux', 'Néovaisseux')], max_length=30, verbose_name='Vaissaux'),
        ),
        migrations.AlterField(
            model_name='segmentposterieur',
            name='vitre',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Corps flottants', 'Corps flottants'), ('Hémorragie', 'Hémorragie'), ('Hyalite', 'Hyalite'), ('PVR', 'PVR'), ('Autres', 'Autres')], max_length=30, verbose_name='Vitre'),
        ),
    ]
