# Generated by Django 5.2 on 2025-05-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_examen', '0006_alter_segmentanterieur_axe_visuel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together=set(),
        ),
    ]
