# Generated by Django 5.2 on 2025-05-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_examen', '0007_alter_segment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomicroscopy',
            name='segment_anterieur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_examen.segmentanterieur'),
        ),
        migrations.AlterField(
            model_name='biomicroscopy',
            name='segment_posterieur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_examen.segmentposterieur'),
        ),
    ]
