# Generated by Django 5.2 on 2025-06-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/images/profiles/avatars/default-profile-picture.png', null=True, upload_to='images/profiles/avatars/users/'),
        ),
    ]
