# Generated by Django 5.2 on 2025-06-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('technician', 'Technician'), ('assistant', 'Assistant')], max_length=13, verbose_name='role'),
        ),
    ]
