# Generated by Django 5.2 on 2025-06-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Administrator'), ('employee', 'Employee'), ('doctor', 'Doctor'), ('technician', 'Technician')], max_length=13, verbose_name='role'),
        ),
    ]
