# Generated by Django 5.2 on 2025-06-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchangecode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signupcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
