# Generated by Django 5.2 on 2025-06-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='image',
            field=models.ImageField(default='media/images/profiles/avatars/default-profile-picture.png', null=True, upload_to='images/profiles/avatars/conducteurs/', verbose_name='Profile picture'),
        ),
    ]
