# Generated by Django 5.2 on 2025-06-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_conducteur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='numero_permis',
            field=models.CharField(db_index=True, max_length=15, unique=True, verbose_name='License number'),
        ),
    ]
