# Generated by Django 5.2 on 2025-06-08 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_conducteur_numero_permis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(db_index=True, default=str(django.utils.timezone.now)[:15], max_length=15, unique=True, verbose_name='Registration'),
            preserve_default=False,
        ),
    ]
