# Generated by Django 5.2 on 2025-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_vehicule_immatriculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='type_permis',
            field=models.CharField(choices=[('leger', 'Light'), ('lourd', 'Heavy'), ('autres', 'Other (please specify)')], verbose_name='License type'),
        ),
    ]
