# Generated by Django 5.2 on 2025-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualacuity',
            name='avac_dg',
            field=models.FloatField(verbose_name='AVAC ODG'),
        ),
        migrations.AlterField(
            model_name='visualacuity',
            name='avac_od',
            field=models.FloatField(verbose_name='AVAC OD'),
        ),
        migrations.AlterField(
            model_name='visualacuity',
            name='avac_og',
            field=models.FloatField(verbose_name='AVAC OG'),
        ),
        migrations.AlterField(
            model_name='visualacuity',
            name='avsc_dg',
            field=models.FloatField(verbose_name='AVSC ODG'),
        ),
        migrations.AlterField(
            model_name='visualacuity',
            name='avsc_od',
            field=models.FloatField(verbose_name='AVSC OD'),
        ),
        migrations.AlterField(
            model_name='visualacuity',
            name='avsc_og',
            field=models.FloatField(verbose_name='AVSC OG'),
        ),
    ]
