# Generated by Django 5.2 on 2025-06-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalexamen',
            name='bp_sup',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.bpsup'),
        ),
    ]
