# Generated by Django 5.2 on 2025-06-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_alter_clinicalexamen_bp_sup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='axe_visuel',
            field=models.CharField(choices=[('DEGAGE', 'DEGAGE'), ('OBSTRUE', 'OBSTRUE'), ('LEUCOCORIE', 'LEUCOCORIE')], max_length=30, verbose_name='Axe Visuel'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='cornee',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('OPACITE_AXE', 'OPACITE_AXE'), ('OPACITE_PERIPHERIE', 'OPACITE_PERIPHERIE'), ('OPACITE_TOTALE', 'OPACITE_TOTALE'), ('AUTRE', 'AUTRE')], max_length=30, verbose_name='Corne'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='cristallin',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('OPAQUE', 'OPAQUE'), ('COLOBOME', 'COLOBOME'), ('APHAKIE', 'APHAKIE'), ('PSEUDOPHAKIE', 'PSEUDOPHAKIE')], max_length=30, verbose_name='Cristallin'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='iris',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('IRIDODONESIS', 'IRIDODONESIS'), ('RUBEOSE', 'RUBEOSE'), ('SYNECHIES', 'SYNECHIES'), ('AUTRES', 'AUTRES')], max_length=30, verbose_name='Iris'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='position_cristallin',
            field=models.CharField(choices=[('NORMALE', 'NORMALE'), ('ECTOPIE', 'ECTOPIE'), ('LUXATION_SUBLUXATION_ANTERIEURE', 'LUXATION_SUBLUXATION_ANTERIEURE'), ('LUXATION_SUBLUXATION_POSTERIEURE', 'LUXATION_SUBLUXATION_POSTERIEURE')], max_length=32, verbose_name='Position Cristallin'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='profondeur',
            field=models.CharField(choices=[('NORMALE', 'NORMALE'), ('REDUITE', 'REDUITE'), ('AUGMENTEE', 'AUGMENTEE'), ('ASYMETRIQUE', 'ASYMETRIQUE')], max_length=30, verbose_name='Profondeur'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='pupille',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('MYOSIS', 'MYOSIS'), ('MYDRIASE', 'MYDRIASE')], max_length=30, verbose_name='Pupille'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='quantite_anomalie',
            field=models.CharField(blank=True, choices=[('MINIME', 'MINIME'), ('ATTEIGNANT_AIR_PUPILLAIRE', 'ATTEIGNANT_AIR_PUPILLAIRE'), ('RECOUVRANT_PUPILLE', 'RECOUVRANT_PUPILLE')], max_length=30, null=True, verbose_name='quantité anomalie'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='rpm',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('LENT', 'LENT'), ('ABOLI', 'ABOLI')], max_length=30, verbose_name='RPM'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='segment',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('PRESENCE_LESION', 'PRESENCE_LESION'), ('REMANIEMENT_TOTAL', 'REMANIEMENT_TOTAL')], max_length=20, verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='transparence',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('ANORMALE', 'ANORMALE')], max_length=30, verbose_name='Transparence'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='type_anomalie_value',
            field=models.CharField(blank=True, choices=[('PIGMENTS', 'PIGMENTS'), ('HYPHEMA', 'HYPHEMA'), ('HYPOPION', 'HYPOPION'), ('AUTRE', 'AUTRE')], max_length=30, null=True, verbose_name='Anormal transparence'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='macula',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('CICATRICE', 'CICATRICE'), ('OEDEME', 'OEDEME'), ('DMLA', 'DMLA')], max_length=30, verbose_name='Macula'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='papille',
            field=models.CharField(choices=[('NORMALE', 'NORMALE'), ('EXCAVATION_ELARGIE', 'EXCAVATION_ELARGIE'), ('ATROPHIE', 'ATROPHIE'), ('OEDEME', 'OEDEME'), ('DYSMORPHIE', 'DYSMORPHIE'), ('AUTRES', 'AUTRES')], max_length=30, verbose_name='Papille'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='retinien_peripherique',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('CICATRICE', 'CICATRICE'), ('OEDEME', 'OEDEME'), ('HEMORRAGIE', 'HEMORRAGIE'), ('EXUDATS', 'EXUDATS'), ('AUTRE', 'AUTRE')], max_length=30, verbose_name='Champ rétinien périphérique'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='segment',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('PRESENCE_LESION', 'PRESENCE_LESION'), ('REMANIEMENT_TOTAL', 'REMANIEMENT_TOTAL')], max_length=20, verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='vaissaux',
            field=models.CharField(choices=[('NORMAUX', 'NORMAUX'), ('ARTERIOSCLEROSE', 'ARTERIOSCLEROSE'), ('OVR', 'OVR'), ('OAR', 'OAR'), ('NEOVAISSEUX', 'NEOVAISSEUX')], max_length=30, verbose_name='Vaissaux'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='vitre',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('CORPS_FLOTTANTS', 'CORPS_FLOTTANTS'), ('HEMORRAGIE', 'HEMORRAGIE'), ('HYALITE', 'HYALITE'), ('PVR', 'PVR'), ('AUTRES', 'AUTRES')], max_length=30, verbose_name='Vitre'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='visite',
            field=models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')], db_index=True),
        ),
        migrations.AlterField(
            model_name='examens',
            name='visite',
            field=models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')], db_index=True),
        ),
        migrations.AlterField(
            model_name='perimetry',
            name='pbo',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('SCOTOME_CENTRAL', 'SCOTOME_CENTRAL'), ('SCOTOME_PERIPHERIQUE', 'SCOTOME_PERIPHERIQUE'), ('AMPUTATION', 'AMPUTATION')], max_length=30, null=True, verbose_name='PBO'),
        ),
        migrations.AlterField(
            model_name='plaintes',
            name='eye_symptom',
            field=models.CharField(choices=[('AUCUN', 'AUCUN'), ('BAV', 'BAV'), ('ROUGEUR', 'ROUGEUR'), ('DOULEUR', 'DOULEUR'), ('DIPLOPIE', 'DIPLOPIE'), ('STARBISME', 'STARBISME'), ('NYSTAGMUS', 'NYSTAGMUS'), ('PTOSIS', 'PTOSIS'), ('AUTRES', 'AUTRES')], max_length=30, verbose_name='OD symptom'),
        ),
        migrations.AlterField(
            model_name='technicalexamen',
            name='visite',
            field=models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')], db_index=True),
        ),
    ]
