# Generated by Django 5.2 on 2025-06-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_alter_visualacuity_avac_dg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaintes',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='plaintes',
            name='visite',
        ),
    ]
