# Generated by Django 5.2 on 2025-06-14 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0003_remove_plaintes_patient_remove_plaintes_visite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalexamen',
            name='ocular_tension',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='examens.oculartension'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technicalexamen',
            name='pachymetry',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='examens.pachymetry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technicalexamen',
            name='refraction',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='examens.refraction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technicalexamen',
            name='visual_acuity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='examens.visualacuity'),
            preserve_default=False,
        ),
    ]
