# Generated by Django 5.2 on 2025-06-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0003_alter_biomicroscopysegmentanterieur_axe_visuel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examens',
            options={'ordering': ['-visite', '-created'], 'verbose_name': 'Examen global', 'verbose_name_plural': 'Examens globaux'},
        ),
    ]
