# Generated by Django 5.2 on 2025-06-15 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0004_alter_technicalexamen_ocular_tension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalexamen',
            name='ocular_tension',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.oculartension'),
        ),
        migrations.AlterField(
            model_name='technicalexamen',
            name='pachymetry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.pachymetry'),
        ),
        migrations.AlterField(
            model_name='technicalexamen',
            name='refraction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.refraction'),
        ),
        migrations.AlterField(
            model_name='technicalexamen',
            name='visual_acuity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.visualacuity'),
        ),
    ]
