# Generated by Django 5.2 on 2025-06-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0004_alter_examens_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examens',
            options={'ordering': ['visite', '-created'], 'verbose_name': 'Examen global', 'verbose_name_plural': 'Examens globaux'},
        ),
    ]
