# Generated by Django 5.2 on 2025-06-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0005_alter_examens_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalexamen',
            name='ocular_tension',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.oculartension'),
        ),
        migrations.AlterField(
            model_name='technicalexamen',
            name='pachymetry',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.pachymetry'),
        ),
        migrations.AlterField(
            model_name='technicalexamen',
            name='refraction',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.refraction'),
        ),
    ]
