# Generated by Django 5.2 on 2025-06-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0005_alter_technicalexamen_ocular_tension_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaintes',
            old_name='od_symptom',
            new_name='eye_symptom',
        ),
        migrations.RemoveField(
            model_name='plaintes',
            name='og_symptom',
        ),
    ]
