# Generated by Django 5.2 on 2025-06-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0006_alter_technicalexamen_ocular_tension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalexamen',
            name='conclusion',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.conclusion'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='od',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='od', to='examens.eyeside'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='og',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='og', to='examens.eyeside'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='perimetry',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.perimetry'),
        ),
    ]
