# Generated by Django 5.2 on 2025-06-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0007_alter_clinicalexamen_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpsup',
            name='autres',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/biomicroscopie/autres/'),
        ),
        migrations.AlterField(
            model_name='bpsup',
            name='oct',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/biomicroscopie/oct/'),
        ),
        migrations.AlterField(
            model_name='bpsup',
            name='retinographie',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/biomicroscopie/retinographie/'),
        ),
        migrations.AlterField(
            model_name='perimetry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/perimetries_binoculaire/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='perimetry',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='media/images/perimetries_binoculaire/', verbose_name='Images'),
        ),
    ]
