# Generated by Django 5.2 on 2025-06-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0008_alter_bpsup_autres_alter_bpsup_oct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refraction',
            name='dp',
        ),
        migrations.AddField(
            model_name='biomicroscopysegmentposterieur',
            name='cd_od',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='C/D OD'),
        ),
        migrations.AddField(
            model_name='biomicroscopysegmentposterieur',
            name='cd_og',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='C/D OG'),
        ),
        migrations.AddField(
            model_name='biomicroscopysegmentposterieur',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='conclusion',
            name='diagnostic_cim_10',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Diagnostic CIM-10'),
        ),
        migrations.AddField(
            model_name='pachymetry',
            name='cto_od',
            field=models.FloatField(default=1, verbose_name='CTO OD (œil droit)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pachymetry',
            name='cto_og',
            field=models.FloatField(default=1, verbose_name='CTO OG (œil gauche)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refraction',
            name='avod',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True, verbose_name='AVOD'),
        ),
        migrations.AddField(
            model_name='refraction',
            name='avog',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True, verbose_name='AVOG'),
        ),
        migrations.AddField(
            model_name='refraction',
            name='correction_optique',
            field=models.BooleanField(default=False, verbose_name='Correction optique'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='axe_visuel',
            field=models.CharField(blank=True, choices=[('DEGAGE', 'DEGAGE'), ('OBSTRUE', 'OBSTRUE'), ('LEUCOCORIE', 'LEUCOCORIE')], default=None, max_length=30, null=True, verbose_name='Axe Visuel'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='cornee',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('OPACITE_AXE', 'OPACITE_AXE'), ('OPACITE_PERIPHERIE', 'OPACITE_PERIPHERIE'), ('OPACITE_TOTALE', 'OPACITE_TOTALE'), ('AUTRE', 'AUTRE')], default=None, max_length=30, null=True, verbose_name='Corne'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='cristallin',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('OPAQUE', 'OPAQUE'), ('COLOBOME', 'COLOBOME'), ('APHAKIE', 'APHAKIE'), ('PSEUDOPHAKIE', 'PSEUDOPHAKIE')], default=None, max_length=30, null=True, verbose_name='Cristallin'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='iris',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('IRIDODONESIS', 'IRIDODONESIS'), ('RUBEOSE', 'RUBEOSE'), ('SYNECHIES', 'SYNECHIES'), ('AUTRES', 'AUTRES')], default=None, max_length=30, null=True, verbose_name='Iris'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='position_cristallin',
            field=models.CharField(blank=True, choices=[('NORMALE', 'NORMALE'), ('ECTOPIE', 'ECTOPIE'), ('LUXATION_SUBLUXATION_ANTERIEURE', 'LUXATION_SUBLUXATION_ANTERIEURE'), ('LUXATION_SUBLUXATION_POSTERIEURE', 'LUXATION_SUBLUXATION_POSTERIEURE')], default=None, max_length=32, null=True, verbose_name='Position Cristallin'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='profondeur',
            field=models.CharField(blank=True, choices=[('NORMALE', 'NORMALE'), ('REDUITE', 'REDUITE'), ('AUGMENTEE', 'AUGMENTEE'), ('ASYMETRIQUE', 'ASYMETRIQUE')], default=None, max_length=30, null=True, verbose_name='Profondeur'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='pupille',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('MYOSIS', 'MYOSIS'), ('MYDRIASE', 'MYDRIASE')], default=None, max_length=30, null=True, verbose_name='Pupille'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='quantite_anomalie',
            field=models.CharField(blank=True, choices=[('MINIME', 'MINIME'), ('ATTEIGNANT_AIR_PUPILLAIRE', 'ATTEIGNANT_AIR_PUPILLAIRE'), ('RECOUVRANT_PUPILLE', 'RECOUVRANT_PUPILLE')], default=None, max_length=30, null=True, verbose_name='quantité anomalie'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='rpm',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('LENT', 'LENT'), ('ABOLI', 'ABOLI')], default=None, max_length=30, null=True, verbose_name='RPM'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='transparence',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('ANORMALE', 'ANORMALE')], default=None, max_length=30, null=True, verbose_name='Transparence'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentanterieur',
            name='type_anomalie_value',
            field=models.CharField(blank=True, choices=[('PIGMENTS', 'PIGMENTS'), ('HYPHEMA', 'HYPHEMA'), ('HYPOPION', 'HYPOPION'), ('AUTRE', 'AUTRE')], default=None, max_length=30, null=True, verbose_name='Anormal transparence'),
        ),
        migrations.AlterField(
            model_name='conclusion',
            name='cat',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='CAT'),
        ),
        migrations.AlterField(
            model_name='conclusion',
            name='observation',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='conclusion',
            name='traitement',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Traitement'),
        ),
        migrations.AlterField(
            model_name='conclusion',
            name='vision',
            field=models.CharField(blank=True, choices=[('compatible', 'Compatible'), ('incompatible', 'Incompatible'), ('a_risque', 'À risque')], default=None, max_length=50, null=True, verbose_name='Conclusion sur la conduite'),
        ),
        migrations.AlterField(
            model_name='refraction',
            name='od_a',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True, verbose_name='A OD'),
        ),
        migrations.AlterField(
            model_name='refraction',
            name='od_c',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True, verbose_name='C OD'),
        ),
        migrations.AlterField(
            model_name='refraction',
            name='od_s',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True, verbose_name='S OD'),
        ),
        migrations.AlterField(
            model_name='refraction',
            name='og_a',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True, verbose_name='A OG'),
        ),
        migrations.AlterField(
            model_name='refraction',
            name='og_c',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True, verbose_name='C OG'),
        ),
        migrations.AlterField(
            model_name='refraction',
            name='og_s',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True, verbose_name='S OG'),
        ),
    ]
