# Generated by Django 5.2 on 2025-06-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0009_remove_refraction_dp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biomicroscopysegmentposterieur',
            options={'verbose_name': 'Segment postérieur (SP)', 'verbose_name_plural': 'Segment postérieurs (SP)'},
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='bp_sup',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicalexamen', to='examens.bpsup'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='conclusion',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicalexamen', to='examens.conclusion'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='od',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='od_clinicalexamen', to='examens.eyeside'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='og',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='og_clinicalexamen', to='examens.eyeside'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='perimetry',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicalexamen', to='examens.perimetry'),
        ),
        migrations.AlterField(
            model_name='eyeside',
            name='bp_sg_anterieur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eyeside', to='examens.biomicroscopysegmentanterieur'),
        ),
        migrations.AlterField(
            model_name='eyeside',
            name='bp_sg_posterieur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eyeside', to='examens.biomicroscopysegmentposterieur'),
        ),
        migrations.AlterField(
            model_name='eyeside',
            name='plaintes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eyeside', to='examens.plaintes'),
        ),
    ]
