# Generated by Django 5.2 on 2025-06-26 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0010_alter_biomicroscopysegmentposterieur_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biomicroscopysegmentposterieur',
            options={'verbose_name': 'Segment antérieur (SA)', 'verbose_name_plural': 'Segment antérieurs (SA)'},
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='bp_sup',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.bpsup'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='conclusion',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.conclusion'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='od',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='od', to='examens.eyeside'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='og',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='og', to='examens.eyeside'),
        ),
        migrations.AlterField(
            model_name='clinicalexamen',
            name='perimetry',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='examens.perimetry'),
        ),
        migrations.AlterField(
            model_name='eyeside',
            name='bp_sg_anterieur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.biomicroscopysegmentanterieur'),
        ),
        migrations.AlterField(
            model_name='eyeside',
            name='bp_sg_posterieur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.biomicroscopysegmentposterieur'),
        ),
        migrations.AlterField(
            model_name='eyeside',
            name='plaintes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.plaintes'),
        ),
    ]
