# Generated by Django 5.2 on 2025-06-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0012_alter_biomicroscopysegmentposterieur_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomicroscopysegmentposterieur',
            name='retine',
        ),
    ]
