# Generated by Django 5.2 on 2025-06-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0013_remove_biomicroscopysegmentposterieur_retine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='macula',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('CICATRICE', 'CICATRICE'), ('OEDEME', 'OEDEME'), ('DMLA', 'DMLA')], default=None, max_length=30, null=True, verbose_name='Macula'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='papille',
            field=models.CharField(blank=True, choices=[('NORMALE', 'NORMALE'), ('EXCAVATION_ELARGIE', 'EXCAVATION_ELARGIE'), ('ATROPHIE', 'ATROPHIE'), ('OEDEME', 'OEDEME'), ('DYSMORPHIE', 'DYSMORPHIE'), ('AUTRES', 'AUTRES')], default=None, max_length=30, null=True, verbose_name='Papille'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='retinien_peripherique',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('CICATRICE', 'CICATRICE'), ('OEDEME', 'OEDEME'), ('HEMORRAGIE', 'HEMORRAGIE'), ('EXUDATS', 'EXUDATS'), ('AUTRE', 'AUTRE')], default=None, max_length=30, null=True, verbose_name='Champ rétinien périphérique'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='vaissaux',
            field=models.CharField(blank=True, choices=[('NORMAUX', 'NORMAUX'), ('ARTERIOSCLEROSE', 'ARTERIOSCLEROSE'), ('OVR', 'OVR'), ('OAR', 'OAR'), ('NEOVAISSEUX', 'NEOVAISSEUX')], default=None, max_length=30, null=True, verbose_name='Vaissaux'),
        ),
        migrations.AlterField(
            model_name='biomicroscopysegmentposterieur',
            name='vitre',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('CORPS_FLOTTANTS', 'CORPS_FLOTTANTS'), ('HEMORRAGIE', 'HEMORRAGIE'), ('HYALITE', 'HYALITE'), ('PVR', 'PVR'), ('AUTRES', 'AUTRES')], default=None, max_length=30, null=True, verbose_name='Vitre'),
        ),
    ]
